[tox]
envlist = py312
isolated_build = true

[pytest]
minversion = 8.0
log_cli = True
log_cli_level = WARNING
addopts = --doctest-modules --doctest-glob="README*"
testpaths =
    README.md
    tests
    pytrms
#   ./examples

[testenv]
allowlist_externals = poetry
commands =
    poetry install -v
    poetry run pytest

